// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZGB3lAC8VId64z6Gk-M8Gs8ZJQ59we-o',
    appId: '1:997603565985:web:c4cc1c91cc7af95173abe0',
    messagingSenderId: '997603565985',
    projectId: 'conecta-facil-flutter-app',
    authDomain: 'conecta-facil-flutter-app.firebaseapp.com',
    storageBucket: 'conecta-facil-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYsLKSk_wRBlU-uXRNX_Uc1_sa7UgA5Z4',
    appId: '1:997603565985:android:5414b9a112a3941d73abe0',
    messagingSenderId: '997603565985',
    projectId: 'conecta-facil-flutter-app',
    storageBucket: 'conecta-facil-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2Ud39Q005ZsMH5ZmKP-F7v-gnWwvK0Ss',
    appId: '1:997603565985:ios:9223343ef509ba9573abe0',
    messagingSenderId: '997603565985',
    projectId: 'conecta-facil-flutter-app',
    storageBucket: 'conecta-facil-flutter-app.firebasestorage.app',
    iosBundleId: 'com.conectafacil.app',
  );
}
